// <auto-generated />
// This file is automatically generated by Entity Framework Core.
// It represents a "snapshot" of the database model at the time of the last migration.
// EF Core uses this to determine what changed when generating future migrations.

using System;
using CardManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardManager.Migrations
{
    // Specifies which DbContext this snapshot belongs to.
    // EF Core uses this to compare schema changes.
    [DbContext(typeof(CardCollectionContext))]
    partial class CardCollectionContextModelSnapshot : ModelSnapshot
    {
        // This method describes the database schema that EF Core knows about.
        // EF compares this snapshot with your model classes to detect changes.
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Stores EF Core metadata such as version information
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            // =============================================================
            // CARD ENTITY
            // Maps to the "Cards" table
            // =============================================================
            modelBuilder.Entity("CardManager.Models.Card", b =>
                {
                    // Primary key (INTEGER AUTOINCREMENT in SQLite)
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    // Optional description text
                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    // Card's name (Required)
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    // Optional monetary value
                    b.Property<decimal?>("Value")
                        .HasColumnType("TEXT");

                    // Primary key configuration
                    b.HasKey("Id");

                    // Table name in the database
                    b.ToTable("Cards");
                });

            // =============================================================
            // DECK ENTITY
            // Maps to the "Decks" table
            // =============================================================
            modelBuilder.Entity("CardManager.Models.Deck", b =>
                {
                    // Primary key
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    // Name of the deck (Required)
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Decks");
                });

            // =============================================================
            // DECKCARD ENTITY (JOIN TABLE)
            // Represents a card belonging to a deck
            // Many-to-many relationship using explicit join entity
            // =============================================================
            modelBuilder.Entity("CardManager.Models.DeckCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    // Foreign key to the Card table
                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    // Foreign key to the Deck table
                    b.Property<int>("DeckId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    // Index for faster queries
                    b.HasIndex("CardId");

                    b.HasIndex("DeckId");

                    b.ToTable("DeckCards");
                });

            // =============================================================
            // RELATIONSHIP CONFIGURATION FOR JOIN TABLE
            // This connects DeckCard -> Card and DeckCard -> Deck
            // =============================================================
            modelBuilder.Entity("CardManager.Models.DeckCard", b =>
                {
                    // Each DeckCard has exactly one Card
                    // Cards can appear in many DeckCards
                    b.HasOne("CardManager.Models.Card", "Card")
                        .WithMany()  // Cards do not keep a list of DeckCards in this snapshot
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)  // Delete DeckCards when Card is deleted
                        .IsRequired();

                    // Each DeckCard belongs to one Deck
                    // Decks have a collection of DeckCards
                    b.HasOne("CardManager.Models.Deck", "Deck")
                        .WithMany("DeckCards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    // Navigation properties
                    b.Navigation("Card");
                    b.Navigation("Deck");
                });

            // Deck navigation collection for DeckCards
            modelBuilder.Entity("CardManager.Models.Deck", b =>
                {
                    b.Navigation("DeckCards");
                });
#pragma warning restore 612, 618
        }
    }
}
